services:
  my_app1:
    # image: python:latest
    build:
      dockerfile: Dockerfile
      context: ./static  
    command: python -m http.server 8000
    ports:
      - 4000:8000
    volumes:
      - ./static/src:/app
  backend:
    # image: python:latest
    build:
      dockerfile: Dockerfile
      context: ./backend  
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - PORT 8000
      - MY_PROJECT_OTHER=/"JBS Consulting"/
    env_file:
      - .env.sample
    ports:
      - 3001:8000
    volumes:
      - ./backend/src:/app
    develop:
      watch:
        - action: rebuild
          path: ./backend/requirements.txt
        - action: rebuild
          path: ./backend/Dockerfile
        - action: restart
          path: ./backend/src
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=ai_agents
      - POSTGRES_PASSWORD=db-password
      - POSTGRES_DB=agent_db
    ports:
      - 5432:5432
    volumes:
      - dc_managed_db_volume:/var/lib/postgresql/data


volumes:
  dc_managed_db_volume: 